.hy 0
.TH rotate_aid 1 "23 May 1992"
.ad

.SH NAME
rotate_aid

.SH DESCRIPTION
rotate_aid is a simple program that helps RotateStream do non-blocking io.

.SH AUTHOR
Eric Lochstet
.sp1
Send bug reports to toolkeeper@msc.cornell.edu
.sp1
rotate_aid was developed at Cornell University as part of the Cornell-IBM Joint
Study on Computing for Scientific Research

