/* Prototypes for all user accessible RANLIB routines */
#ifndef _NO_PROTO
extern void advnst(long k);
extern float genbet(float aa,float bb);
extern float genchi(float df);
extern float genexp(float av);
extern float genf(float dfn, float dfd);
extern float gengam(float a,float r);
extern void genmn(float *parm,float *x,float *work);
extern float gennch(float df,float xnonc);
extern float gennf(float dfn, float dfd, float xnonc);
extern float gennor(float av,float sd);
extern void genprm(long *iarray,int larray);
extern float genunf(float low,float high);
extern void getsd(long *iseed1,long *iseed2);
extern void gscgn(long getset,long *g);
extern long ignbin(long n,float pp);
extern long ignlgi(void);
extern long ignpoi(float mu);
extern long ignuin(long low,long high);
extern void initgn(long isdtyp);
extern long mltmod(long a,long s,long m);
extern void phrtsd(char* phrase,long* seed1,long* seed2);
extern float ranf_really(void);
extern float ranf(void);
extern void setall(long iseed1,long iseed2);
extern void setant(long qvalue);
extern void setgmn(float *meanv,float *covm,long p,float *parm);
extern void setsd(long iseed1,long iseed2);
extern float sexpo(void);
extern float sgamma(float a);
extern float snorm(void);
extern void inrgcm(void);
extern float fsign(float a, float b);
#else
extern void advnst();
extern float genbet();
extern float genchi();
extern float genexp();
extern float genf();
extern float gengam();
extern void genmn();
extern float gennch();
extern float gennf();
extern float gennor();
extern void genprm();
extern float genunf();
extern void getsd();
extern void gscgn();
extern long ignbin();
extern long ignlgi();
extern long ignpoi();
extern long ignuin();
extern void initgn();
extern long mltmod();
extern void phrtsd();
extern float ranf_really();
extern float ranf();
extern void setall();
extern void setant();
extern void setgmn();
extern void setsd();
extern float sexpo();
extern float sgamma();
extern float snorm();
extern void inrgcm();
extern float fsign();
#endif
