      SUBROUTINE RFFTI (N,WSAVE)

      IMPLICIT DOUBLE PRECISION (A-H), DOUBLE PRECISION (O-Z)

      DIMENSION       WSAVE(1)
      IF (N .EQ. 1) RETURN
      CALL RFFTI1 (N,WSAVE(N+1),WSAVE(2*N+1))
      RETURN
      END
