BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q 
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin 
END_DEF = ****************************

SRCS = \
	blend.c

OBJS = \
	blend.o

all: blend

.c.o:
	$(CC) $(CFLAGS) $(SRCS) $(EXTRA)

blend: $(OBJS)
	$(CC) -o blend $(OBJS) -lm

clean::
	rm -f *.o blend

install::
	cp -p blend $(BINDIR)
	chmod 775 $(BINDIR)/blend


	