.hy 0
.TH MSOLVE 1 "24 July 1991"
.ad

.SH NAME
MSolve - a program for solving linear equations

.SH SYNOPSIS

.B MSolve 
[ 
.I -options 
]

.SH DESCRIPTION
MSolve is a program for solving linear equations of the form Ax = B,
where A and B are known and x is unknown. MSolve accepts matrices from
standard input and writes the solution to standard output. The matrix A must
be invertable but B can be any matrix that has the same number of rows as the
matrix A has columns. MSolve uses the double precision Linpack routines 
to perform its calculations.

.SH USAGE
To use MSolve you need a file containing matrices or you can also
type matrices into MSolve directly. MSolve will continue to process
matrices until it reads and EOF, end of file, character. Each row of the
matrix can be punctuated with newlines, braces, { }, or brackets, [ ] but the
punctuation must be consistent throughout the matrix. The beginning and ending
punctuation of each matrix must be consistent with that of its rows. The rows
and matrices that end with a newline do not have any beginning punctuation.
MSolve can also read matrices in binary form, which is much faster. For
more information about the binary mode, see the math_io documentation.
MSolve accepts complex numbers in several formats: (a,b), a+bi, or a+bI,
where 'a' is the real part and 'b' is the imaginary part. 
.sp1
MSolve will also estimate the reciprocal condition of the matrix, if it
is called with the -condition option. MSolve will print the reciprocal
condition to standard output if no output file is specified with the
-file_condition option. For more information about the reciprocal condition,
 see the 
.I
Linpack Users' Guide
by Dongarra et al.

.SH OPTIONS
-real : The matrix elements of A nad B are real numbers; the default mode. 
.LP
-complex : The matrix elements of A and B are complex numbers. 
.LP
-general : Uses routines that work with all matrices, the default mode.
.LP
-symmetric : Uses routines optimized for symmetric matrices, real or complex.
.LP
-hermitian : Uses routines optimized for hermitian matrices, complex only.
.LP
-upper_triangular : Uses routines optimized for upper triangular matrices.
.LP
-lower_triangular : Uses routines optimized for lower triangular matrices.
.LP
-binary_Ain : Inputs the A matrices in binary form.
.LP
-binary_Bin : Inputs the B matrices in binary form.
.LP
-binary_out : Outputs the x matrices in binary form.
.LP
-file_in 
.I file 
: Specifies the default 
.I file 
the matrices are read from.
.LP
-file_Ain 
.I file 
: Specifies the 
.I file 
the A matrices are read from.
.LP
-file_Bin 
.I file 
: Specifies the 
.I file 
the B matrices are read from.
.LP
-file_out 
.I file 
: Specifies the 
default output 
.I file.
.LP
-file_Xout 
.I file 
: Specifies the 
.I file 
the x matrices are written to.
.LP
-file_condition 
.I file 
: Specifies the 
.I file 
the conditions are written to.
.LP
The output files can also be 'stderr' to output to standard error.
.LP
-condition : Estimates the reciprocal conditions of the matrices.
.LP
-timing : Prints timing information to standard error.
.LP
? , -? , -h , -help : Print help information to standard error.

.SH DEFAULTS
The default mode for MSolve is to read two real matrices A and B from
standard input and write the solution x of Ax = B to standard output.

.SH EXAMPLE
.sp 1
   MSolve -file_Ain Adata -file_Bin Bdata -hermitian -file_out results
.sp 1
will read hermitian matrices from the file Adata, and any type of matrix from the file Bdata and write the solution x to the file results. (The -complex
flag is unnecessary for hermitian matrices.)

.SH "SEE ALSO"
DI, MMult

.SH BUGS
1 - Does not support the Mathematica arrow notation to denote an exponent.
.PP
2 - Does not support the Fortran 'd' notation.
.PP
3 - "MSolve -real -hermitian"
will use complex hermitian matrices, not real matrices and produces no error 
message.

.SH AUTHOR
Eric Lochstet
.sp1
Send bug reports to toolkeeper@msc.cornell.edu
.sp1
MSolve was developed at Cornell University as part of the
Cornell-IBM Joint Study on Computing for Scientific Research










