#!/usr/bin/perl -w
use Chart::Graph::Gnuplot qw(gnuplot);

    my %cols = (
                1 => "Bandwidth Utilization IN", ####CHECK
                2 => "Bandwidth Utilization OUT", ####CHECK
		3 => "Threshold", ####CHECK
		4 => "Capacity"
		#Use below with latency or redundancy data included
		#4 => "Bandwidth Utilization IN", 
                #5 => "Bandwidth Utilization OUT",
		#6 => "Threshold"
                );
    gnuplot({
             "title" => "Chandlers Ford 1.7Mbit LINK In/Out COMBINED traffic", ####CHECK
             "x-axis label" => "Mon-Fri 08am-18pm traffic", ####CHECK
             "y-axis label" => "Kbits/sec Utilization",
             "output type" => "png",
             "output file" => "chandlers-ford-combined-08am-18pm-1Mb.png", ####CHECK
	     #"xtics" => [ ["combined-traffic for Lord and Mosley street", 1000] ],
	     "xtics" => [ ["4 weeks duration", 100] ], 
             # Setting date/time specific options.
             #"xdata" => "%m/%y",
             #"timefmt" => "%m", 	
             #"format" => ["x", "%m"],
             # Set output range - note quoting of date string
             #"xrange" => "[\"18/06/2004\":\"02/07/2004\"]",
	     #"extra_opts" => join("\n", "set grid"),
            },

            map {  
                [{"title" => $cols{$_},
                  "style" => "linespoints",
                  "type" => "file",
                  using => "$_" },
                 "gnuplot-data.txt"] } (sort keys %cols));

