BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q 
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin
END_DEF = ****************************

SRCS = \
	branch.c

OBJS = \
	branch.o

all: branch

.c.o:
	$(CC) $(CFLAGS) $(INCDIR) $(SRCS) $(EXTRA)

branch: $(OBJS)
	$(CC) -o branch $(OBJS) -lm 

clean::
	rm -f *.o branch

install::
	cp -p branch $(BINDIR)
	chmod 775 $(BINDIR)/branch


	