BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q 
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
XM_LIBS = -lXm -lXt -lX11
BINDIR = ../bin
END_DEF = ****************************

SRCS = \
	items.c

OBJS = \
	items.o

all: items

.c.o:
	$(CC) $(CFLAGS) $(SRCS) $(EXTRA)

items: $(OBJS)
	$(CC) -o items $(OBJS) $(XM_LIBS) -lm 

clean::
	rm -f *.o items

install::
	cp -p items $(BINDIR)
	chmod 775 $(BINDIR)/items
