BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q 
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin
END_DEF = ****************************

SRCS = \
	laser.c

OBJS = \
	laser.o

all: laser

.c.o:
	$(CC) $(CFLAGS) $(INCDIR) $(SRCS) $(EXTRA)

laser: $(OBJS)
	$(CC) -o laser $(OBJS) -lm 

clean::
	rm -f *.o laser

install::
	cp -p laser $(BINDIR)
	chmod 775 $(BINDIR)/laser



	