#!/usr/bin/perl -w
use Chart::Graph::Gnuplot qw(gnuplot);

    my %cols = (
                1 => "Bandwidth Utilization IN", ####CHECK
                2 => "Bandwidth Utilization OUT", ####CHECK
		3 => "Threshold" ####CHECK
		#4 => "2MB Capacity"
		#Use below with latency data included
		#4 => "Bandwidth Utilization IN", 
                #5 => "Bandwidth Utilization OUT",
		#6 => "Threshold"
                );
    gnuplot({
             "title" => "Site Traffic hour-stats-data-15-wsi 60MB LINK In/Out traffic", ####CHECK
	     #"title" => "Childs Bank 128KB ISDN Backup Link Mon-Fri traffic 8am-18pm", ####CHECK
             "x-axis label" => "Mon's-Fri's hour-stats-data-15-wsi traffic peak time", ####CHECK
             #"x-axis label" => "about 3 days duration", ####CHECK
             "y-axis label" => "Kbits/sec Utilization",
             #"y-axis label" => "Kbytes/sec Utilization",
             "output type" => "png",
             "output file" => "hour-stats-data-15-wsi-60MB.png", ####CHECK
             #"output file" => "fettesrow-mosley-wkend.png", ####CHECK
	     #"xtics" => [ ["combined-traffic for Lord and Mosley street", 1000] ],
	     "xtics" => [ ["hour-stats-data-15-wsi", 1000] ], 
             # Setting date/time specific options.
             #"xdata" => "%m/%y",
             #"timefmt" => "%m",	
             #"format" => ["x", "%m"],
             # Set output range - note quoting of date string
             #"xrange" => "[\"18/06/2004\":\"02/07/2004\"]",
	     #"extra_opts" => join("\n", "set grid"),
            },

            map {  
                [{"title" => $cols{$_},
                  "style" => "linespoints",
                  "type" => "file",
                  using => "$_" },
                 "data"] } (sort keys %cols));

