BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q 
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin
END_DEF = ****************************

SRCS = \
	bonds.c

OBJS = \
	bonds.o

all: bonds

.c.o:
	$(CC) $(CFLAGS) $(INCDIR) $(SRCS) $(EXTRA)

bonds: $(OBJS)
	$(CC) -o bonds $(OBJS) -lm 

clean::
	rm -f *.o bonds

install::
	cp -p bonds $(BINDIR)
	chmod 775 $(BINDIR)/bonds


	