BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin
END_DEF = ****************************

SRCS = \
	histogram.c

OBJS = \
	histogram.o

all: histogram

.c.o:
	$(CC) $(CFLAGS) $(SRCS) $(EXTRA)

histogram: $(OBJS)
	$(CC) -o histogram $(OBJS) -lm

clean::
	rm -f *.o histogram

install::
	cp -p histogram $(BINDIR)
	chmod 775 $(BINDIR)/histogram


	