BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q 
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin 
END_DEF = ****************************

SRCS = \
	thin.c \
	whitespace.c

OBJS = \
	thin.o \
	whitespace.o


all: thin

.c.o:
	$(CC) $(CFLAGS) $(SRCS) $(EXTRA)

thin: $(OBJS)
	$(CC) -o thin $(OBJS) -lm 

clean::
	rm -f *.o thin

install::
	cp -p thin $(BINDIR)
	chmod 775 $(BINDIR)/thin


	