#!/usr/bin/perl -w
use Chart::Graph::Gnuplot qw(gnuplot);

    my %cols = (
                2 => "MIN", ####CHECK
                3 => "AVG", ####CHECK
		4 => "MAX" ####CHECK
		#7 => "Capacity"
		#Use below with latency or redundancy data included
		#4 => "Bandwidth Utilization IN", 
                #5 => "Bandwidth Utilization OUT",
		#6 => "Threshold"
                );
    gnuplot({
             "title" => "Harrogate RTT", ####CHECK
	     #"title" => "Childs Bank 128KB ISDN Backup Link Mon-Fri traffic 8am-18pm", ####CHECK
             "x-axis label" => "Packet Size (bytes)", ####CHECK
             #"x-axis label" => "about 3 days duration", ####CHECK
             "y-axis label" => "Delay (ms)",
             "output type" => "png",
             "output file" => "Harrogate-rtt.png", ####CHECK
	     #"xtics" => [ ["Packet Size (bytes)", 100] ], 
             # Setting date/time specific options.
             #"xdata" => "%m/%y",
             #"timefmt" => "%m",	
             #"format" => ["x", "%m"],
             # Set output range - note quoting of date string
             "xrange" => "[0:1500]",
	     #"extra_opts" => join("\n", "set grid"),
            },

            map {  
                [{"title" => $cols{$_},
                  "style" => "linespoints",
                  "type" => "file",
                  using => "1:$_" },
                 "data"] } (sort keys %cols));

