.hy 0
.TH INTERPRETER 3S "February 24 1992"
.ad

.SH NAME
interpreter \- standard command line interpreter package written in C++

.SH SYNOPSIS
.B #include "Array.h"
.B #include "ErrorHandler.h"
.B #include "HTable.h"
.B #include "Index.h"
.B #include "Interpreter.h"

.SH DESCRIPTION

This is a set of C++ class definitions, designed to be general support for 
command line interpreters.


.SH USAGE


.SH AVAILABLE ROUTINES:


.SH FILES


.SH "SEE ALSO"


.SH BUGS


.SH AUTHOR

.sp1
Send bug reports to toolkeeper@msc.cornell.edu
.sp1
