#!/usr/bin/perl -w
use Chart::Graph::Gnuplot qw(gnuplot);

    my %cols = (
                3 => "Bandwidth Utilization IN", ####CHECK
                4 => "Bandwidth Utilization OUT", ####CHECK
		5 => "Threshold" ####CHECK
		#6 => "Capacity"
		#Use below with latency or redundancy data included
		#4 => "Bandwidth Utilization IN", 
                #5 => "Bandwidth Utilization OUT",
		#6 => "Threshold"
                );
    gnuplot({
             "title" => "Rotheram and Redhill Combined Traffic 10Mb PVC LINK In/Out traffic", ####CHECK
	     #"title" => "Childs Bank 128KB ISDN Backup Link Mon-Fri traffic 8am-18pm", ####CHECK
             "x-axis label" => "Mon-Fri 14pm-15pm traffic", ####CHECK
             #"x-axis label" => "about 3 days duration", ####CHECK
             "y-axis label" => "Kbits/sec Utilization",
             #"y-axis label" => "Kbytes/sec Utilization",
             "output type" => "png",
             "output file" => "rotheram-redhill-combined-14pm-15pm-10Mb.png", ####CHECK
             #"output file" => "fettesrow-mosley-wkend.png", ####CHECK
	     #"xtics" => [ ["combined-traffic for Lord and Mosley street", 1000] ],
	     "xtics" => [ ["2 weeks duration", 100] ], 
             # Setting date/time specific options.
             #"xdata" => "%m/%y",
             #"timefmt" => "%m", 	
             #"format" => ["x", "%m"],
             # Set output range - note quoting of date string
             #"xrange" => "[\"18/06/2004\":\"02/07/2004\"]",
	     #"extra_opts" => join("\n", "set grid"),
            },

            map {  
                [{"title" => $cols{$_},
                  "style" => "linespoints",
                  "type" => "file",
                  using => "$_" },
                 "data.txt"] } (sort keys %cols));

