sed 's/,/ /g' FR*.txt | awk '{ print $1,$3,$4,$5,$6 }' > busy-data; 
./busy-hr-stats.pl; 
./chart-graph-00; 
./chart-graph-01; 
./chart-graph-02; 
./chart-graph-03;  
./chart-graph-04;  
./chart-graph-05; 
./chart-graph-06;  
./chart-graph-07; 
./chart-graph-08; 
./chart-graph-09; 
#awk '/10:.*/' busy-data > data; ./chart-graph-10; 
#awk '/11:.*/' busy-data > data; ./chart-graph-11; 
#awk '/12:.*/' busy-data > data; ./chart-graph-12; 
#awk '/13:.*/' busy-data > data; ./chart-graph-13; 
#awk '/14:.*/' busy-data > data; ./chart-graph-14; 
#awk '/15:.*/' busy-data > data; ./chart-graph-15; 
#awk '/16:.*/' busy-data > data; ./chart-graph-16; 
#awk '/17:.*/' busy-data > data; ./chart-graph-17;  
#awk '/18:.*' busy-data > data; ./chart-graph-18; 
#awk '/19:.*/' busy-data > data; ./chart-graph-19; 
#awk '/20:.*/' busy-data > data; ./chart-graph-20; 
#awk '/21:.*/' busy-data > data; ./chart-graph-21; 
#awk '/22:.*/' busy-data > data; ./chart-graph-22; 
#awk '/23:.*/' busy-data > data; ./chart-graph-23;  
