#!/bin/bash

sed 's/,/ /g' RHGIBGP1-14Mbps-PVC-Harrogate-to-FRCIBGP2.csv | awk '{ print $1,$3,$4,$5,$6 }' > busy-data; 

echo '########## CREATING 00:00-00:55 STATISTICS and GRAPH ##########';
echo '##################################################################' > busy-data-stats; echo '#    		          00:00-00:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/00:.*:00/' busy-data > hour-stats-data-00; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-00 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-00; echo '########## 00:00-00:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 01:00-01:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          01:00-01:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/01:.*:00/' busy-data > hour-stats-data-01; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-01 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-01; echo '########## 01:00-01:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 02:00-02:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          02:00-02:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/02:.*:00/' busy-data > hour-stats-data-02; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-02 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-02; echo '########## 02:00-02:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 03:00-03:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          03:00-03:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/03:.*:00/' busy-data > hour-stats-data-03; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-03 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-03; echo '########## 03:00-03:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 04:00-04:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          04:00-04:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/04:.*:00/' busy-data > hour-stats-data-04; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-04 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-04; echo '########## 04:00-04:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 05:00-05:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          05:00-05:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/05:.*:00/' busy-data > hour-stats-data-05; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-05 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-05; echo '########## 05:00-05:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 06:00-06:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          06:00-06:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/06:.*:00/' busy-data > hour-stats-data-06; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-06 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-06; echo '########## 06:00-06:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 07:00-07:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          07:00-07:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/07:.*:00/' busy-data > hour-stats-data-07; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-07 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-07; echo '########## 07:00-07:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 08:00-12:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          08:00-08:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/08:.*:00/' busy-data > hour-stats-data-08; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-08 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-08; echo '########## 08:00-08:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 09:00-09:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          09:00-09:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/09:.*:00/' busy-data > hour-stats-data-09; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-09 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-09; echo '########## 09:00-09:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 10:00-10:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          10:00-10:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/10:.*:00/' busy-data > hour-stats-data-10; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-10 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-10; echo '########## 10:00-10:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 11:00-11:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          11:00-11:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/11:.*:00/' busy-data > hour-stats-data-11; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-11 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-11; echo '########## 11:00-11:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 12:00-12:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          12:00-12:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/12:.*:00/' busy-data > hour-stats-data-12; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-12 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-12; echo '########## 12:00-12:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 13:00-13:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          13:00-13:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/13:.*:00/' busy-data > hour-stats-data-13; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-13 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-13; echo '########## 13:00-13:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 14:00-14:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          14:00-14:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/14:.*:00/' busy-data > hour-stats-data-14; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-14 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-14; echo '########## 14:00-14:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 15:00-15:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          15:00-15:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/15:.*:00/' busy-data > hour-stats-data-15; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-15 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-15; echo '########## 15:00-15:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 16:00-16:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          16:00-16:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/16:.*:00/' busy-data > hour-stats-data-16; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-16 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-16; echo '########## 16:00-16:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 17:00-17:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          17:00-17:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/17:.*:00/' busy-data > hour-stats-data-17; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-17 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-17; echo '########## 17:00-17:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 18:00-18:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          18:00-18:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/18:.*:00/' busy-data > hour-stats-data-18; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-18 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-18; echo '########## 18:00-18:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 19:00-19:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          19:00-19:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/19:.*:00/' busy-data > hour-stats-data-19; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-19 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-19; echo '########## 19:00-19:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 20:00-20:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          20:00-20:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/20:.*:00/' busy-data > hour-stats-data-20; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-20 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-20; echo '########## 20:00-20:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 21:00-21:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          21:00-21:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/21:.*:00/' busy-data > hour-stats-data-21; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-21 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-21; echo '########## 21:00-21:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 22:00-22:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          22:00-22:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/22:.*:00/' busy-data > hour-stats-data-22; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-22 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-22; echo '##########  22:00-22:55 STATISTICS and GRAPH CREATED ##########';

echo '########## CREATING 23:00-23:55 STATISTICS and GRAPH ##########';
echo '##################################################################' >> busy-data-stats; echo '#    		          23:00-23:55				 #' >> busy-data-stats; echo '##################################################################' >> busy-data-stats; awk '/23:.*:00/' busy-data > hour-stats-data-23; gcc -lm avg-per-in.c; awk '{ print $3, $4 }' hour-stats-data-23 > stats; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm avg-per-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm values-in.c; awk '{ print $1 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm values-out.c; awk '{ print $2 }' stats | ./a.out | grep MAX >> busy-data-stats; gcc -lm histrogram-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm histrogram-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-in.c; awk '{ print $1 }' stats | ./a.out >> busy-data-stats; gcc -lm distribution-out.c; awk '{ print $2 }' stats | ./a.out >> busy-data-stats; ./chart-graph-23; echo '########## 23:00-23:55 STATISTICS and GRAPH CREATED ##########';
