#!/usr/bin/perl -w
use Chart::Graph::Gnuplot qw(gnuplot);

    my %cols = (
                2 => "Data",
                3 => "ackData"
		#4 => "synData"
		#Use below with latency data included
		#4 => "Bandwidth Utilization IN", 
                #5 => "Bandwidth Utilization OUT",
		#6 => "Threshold"
                );
    gnuplot({
             #"title" => "Melville Gate to Lord Street on 22MB PVC LINK  In/Out Weekend traffic",
	     "title" => "50.144 > 10.221",
             #"x-axis label" => "2 week duration",
             "x-axis label" => "time",
             #"y-axis label" => "Kbits/sec Utilization",
             "y-axis label" => "bytes/sec",
             "output type" => "png",
             "output file" => "tcpdump-graph.png",
	     #"xtics" => [ ["Login trace", 5] ],
             # Setting date/time specific options.
             #"xdata" => "time",
	     #"timefmt" => "%S",
             #"format" => ["x", "%S"],
             # Set output range - note quoting of date string
             #"xrange" => "[0.000000:-45.000043]",
             "extra_opts" => join("\n", "set grid"),
            },

            map {  
                [{"title" => $cols{$_},
                  "style" => "linespoints",
                  "type" => "file",
                  using => "0:$_" },
                 "graph"] } (sort keys %cols));

