BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin
END_DEF = ****************************

SRCS = \
	translate.c

OBJS = \
	translate.o

all: translate

.c.o:
	$(CC) $(CFLAGS) $(SRCS) $(EXTRA)

translate: $(OBJS)
	$(CC) -o translate $(OBJS) 

clean::
	rm -f *.o translate

install::
	cp -p translate $(BINDIR)
	chmod 775 $(BINDIR)/translate


	