BEGIN_DEF = ***************************
CFLAGS = -c -O -K -Q 
CFLAGS_SUN = -c -O -DSUN -D_NO_PROTO -DSTRINGS_ALIGNED -DNO_REGEX -DNO_ISDIR -DUSE_RECOMP -DUSE_GETWD -DUNDERSCOREFORTRAN
BINDIR = ../bin
END_DEF = ****************************

SRCS = \
	pre_gr.c

OBJS = \
	pre_gr.o

all: pre_gr

.c.o:
	$(CC) $(CFLAGS) $(INCDIR) $(SRCS) $(EXTRA)

pre_gr: $(OBJS)
	$(CC) -o pre_gr $(OBJS) -lm 

clean::
	rm -f *.o pre_gr

install::
	cp -p pre_gr $(BINDIR)
	chmod 775 $(BINDIR)/pre_gr



	