.hy 0
.TH POLYDRAW3D 1 "18  May 1991"
.ad

.SH NAME
polydraw3D - a polygon drawing program


.SH SYNOPSIS

.B polydraw
< 
.I datafile

.SH DESCRIPTION
Polydraw3D is an X Window System plotting package which reads a series of
polygon specifications from standard input and draws them in color in a window.
Polygons can be drawn continuously into the window with optional clearing of
window when specified, or the polygons can be plotted off-screen and sent to
the screen one-frame-at-a-time as in an animation.
.LP
Polydraw3D will function on any X11R4 or X11R3 Window server. 

.SH USAGE
To use polydraw, you need a data file with multiple x-y-z triples on each line
followed by a color specifications which begins with an arbitrary string and is
followed by three integers representing the red, green and blue components of 
the color.  

For example a line in the file might read-

1 1 1 1 -1 1 -1 -1 1 -1 1 1 rgb 65535 0 0

This line produces a completely red square.

.LP
If colors are specified they will be used to fill the polygon or draw the
frame in
nofill mode.  In line mode they are used to color the lines.  If colors are not
specified ("-nocolors" option) the lines and frames appear in black and the
polygons are filled in white.

.sp1

.SH OPTIONS
.LP
-nocolors	:	do not read in colors (gives black&white)
.LP
-nofill		:	do not fill polygons (wireframe: faster)
.LP
-noframe	:	do not draw frames around each polygon
.LP
-p or -perspective :  draws polygons in perspective mode
.LP
-i or -interactive :  'interactive' - see each polygon as it is read
.LP
-buffer : accumulate polygons - draw as 'frames'
.LP
-b or -binary : binary mode input
.LP
-pval 
.I number 
: Set perspective constants, automatically turns perspective mode on
.I number 
.LP
-max 
.I number 
: Set maximum value corresponding to the edge of the window
.I number 
.LP
-g or -geometry : request window geometry in standard X format
.LP
-title 
.I string 
: Set window title to 
.I string
.LP
-help or -h : print brief help information
.LP
.sp1
.sp1

.SH DEFAULTS
There are hard-coded defaults that polydraw3D uses if no options are specified
on the command line.  The default for max are 1.0, and 1.0 for pval.The window
is titled "polydraw3D".


.SH CONTROLS
While in the window dragging the pointer with the left mouse button dowm will
cause the image to be rotated with the motion of the mouse.
In addition while in the window the pressing of the following keys produces 
the following responses. (not case sensitive)
b:  toggle buffermode on/off
c:  toggle colors on/off
f:  toggle fill on/off
i:  toggle interactive mode on/off
p:  toggle perspective on/off
q:  quit polydraw3D
+:  zoom in
-:  zoom out


.SH EXAMPLES
.sp 1
   polydraw3D -title "Carbon Molecules" -buffer < C216uc
   
   cat testdata | polydraw3D -noframe
.sp 1

.SH "SEE ALSO"
3D-2D, RotateStream, plotatoms

.SH BUGS
.nf
Some examples-
1. In buffer mode with no backing store, an expose event causes the
   the window to heal with the current contents of the buffer which
   is being prepared to become the next frame.
2. Polydraw3D does not handle resizing of its window.
3. Background and frame colors should be user-specifiable.
.fi

.SH AUTHOR
Jeffrey Cohen and Mark Zukowsky
.sp1
Send bug reports to toolkeeper@msc.cornell.edu
.sp1
Polydraw3D was developed at Cornell University as part of the Cornell-IBM Joint
Study on Computing for Scientific Research
